<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SharpAccess.PackageTests</AssemblyName>
    <RootNamespace>SharpAccess.PackageTests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../src/SharpAccess.Core/SharpAccess.Core.csproj" />
    <ProjectReference Include="../../providers/SharpAccess.Sqlite/SharpAccess.Sqlite.csproj" />
    <ProjectReference Include="../../providers/SharpAccess.Postgres/SharpAccess.Postgres.csproj" />
    <ProjectReference Include="../../tools/SharpAccess.Sbom/SharpAccess.Sbom.csproj" ReferenceOutputAssembly="false" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="All" />
    <PackageReference Include="coverlet.collector" PrivateAssets="All" />
  </ItemGroup>
</Project>
